// <auto-generated />
using DiscountGrpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscountGrpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20240513211219_Add Over and OverAmount props in Coupon model")]
    partial class AddOverandOverAmountpropsinCouponmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DiscountGrpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Over")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OverAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1,
                            Description = "OP from te future",
                            Over = 0,
                            OverAmount = 0,
                            ProductName = "One Plus 21"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 99,
                            Description = "QUALQUER MOTOBOMBA",
                            Over = 0,
                            OverAmount = 0,
                            ProductName = "MOTOBOSTA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
